fileFormatVersion: 2
guid: 78b80371aabba1d48aac39ec7ccfe7c5
DefaultImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
AssetOrigin:
  serializedVersion: 1
  productId: 129321
  packageName: Mirror
  packageVersion: 93.0.1
  assetPath: Assets/Mirror/Hosting/Edgegap/Dockerfile
  uploadId: 698109
